# SQLite version 3.x
#   gem install sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: shop_development
  pool: 5
  username: root

test:
  adapter: postgresql
  encoding: unicode
  database: shop_test
  pool: 5
  username: root
