# SQLite version 3.x
#   gem install sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: d5tjhtg05li0mf
  pool: 5
  username: sbupfgrifhrwvd
  password:  fJq2D22vrG1KCrGI7vcFzhzKhx

test:
  adapter: postgresql
  encoding: unicode
  database: d5tjhtg05li0mf
  pool: 5
  username: sbupfgrifhrwvd
  password:  fJq2D22vrG1KCrGI7vcFzhzKhx